// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data.Context;

#nullable disable

namespace Shop.Data.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "Latest iPhone model",
                            Name = "Apple iPhone 14",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sports",
                            Description = "High-performance basketball shoes",
                            Name = "Nike Air Jordan",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Description = "High-definition TV with 4K resolution",
                            Name = "Samsung 4K TV",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Clothing",
                            Description = "Classic denim jeans",
                            Name = "Levi's Jeans",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            Description = "Professional-grade digital camera",
                            Name = "Canon EOS Camera",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sports",
                            Description = "Classic basketball shoes",
                            Name = "Adidas Superstar Shoes",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            Description = "Next-generation gaming console",
                            Name = "Sony PlayStation 5",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Clothing",
                            Description = "High-quality cotton T-shirt",
                            Name = "Calvin Klein T-Shirt",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            Description = "High-performance laptop for business",
                            Name = "Dell Laptop",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Sports",
                            Description = "High-performance cross-training shoes",
                            Name = "Reebok CrossFit Shoes",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Home Appliances",
                            Description = "High-capacity refrigerator with advanced features",
                            Name = "LG Refrigerator",
                            Price = 2499.00m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Clothing",
                            Description = "High-quality athletic hoodie",
                            Name = "Under Armour Hoodie",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Software",
                            Description = "Productivity software suite",
                            Name = "Microsoft Office Software",
                            Price = 149.00m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Electronics",
                            Description = "High-quality wireless headphones",
                            Name = "Bose Headphones",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Sports",
                            Description = "High-performance soccer cleats",
                            Name = "Puma Soccer Cleats",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Home Appliances",
                            Description = "High-capacity washing machine with advanced features",
                            Name = "Whirlpool Washing Machine",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Accessories",
                            Description = "High-quality sunglasses with polarized lenses",
                            Name = "Ray-Ban Sunglasses",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Electronics",
                            Description = "High-quality inkjet printer for home use",
                            Name = "HP Printer",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Clothing",
                            Description = "High-quality waterproof jacket for outdoor activities",
                            Name = "The North Face Jacket",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Electronics",
                            Description = "High-performance smartwatch with fitness tracking features",
                            Name = "Fitbit Smartwatch",
                            Price = 249.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
